namespace media_foundation_codecs
{
    [default_interface]
    runtimeclass MediaFoundationEncoder
    {
        MediaFoundationEncoder();
        
        void Initialize();
        UInt8[] ProcessFrame(UInt8[] data, Int64 timestamp);
        void Shutdown();
    }
}
